site_name: 微积分与解析几何（在线中文版）
theme: 
  language: zh
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - toc.follow
nav:
  - 首页: index.md
  - 第1章 数、函数与图像:
    - 1.1 导论: 1/1.md
    - 1.2 数轴与坐标平面 毕达哥拉斯: 1/2.md
  - 第19章 偏导数:
      - 19.3 曲面的切平面: 19/3.md
      - 19.4 增量和微分 基本引理: 19/4.md
plugins: 
  - blog
markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
extra_javascript:
  - assets/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js