site_name: 微积分与解析几何（在线中文版）
site_url: https://mitochondriacn.github.io/cwag-chinese/
theme: 
  language: zh
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.footer
    - toc.follow
    - search.suggest
    - content.action.view
  icon:
    view: material/eye
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 切换到浅色模式
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: 跟随系统深浅色模式
nav:
  - 首页: index.md
  - 第1章 数、函数与图像:
    - 1.1 导论: 1/1.md
    - 1.2 数轴与坐标平面 毕达哥拉斯: 1/2.md
  - 第19章 偏导数:
      - 19.3 曲面的切平面: 19/3.md
      - 19.4 增量和微分 基本引理: 19/4.md
      - 19.5 方向导数和梯度: 19/5.md
plugins: 
  - blog
  - search:
      lang: zh
      jieba_dict: dict.txt
markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences
repo_url: https://github.com/MitochondriaCN/cwag-chinese
repo_name: MitochondriaCN/cwag-chinese
edit_uri: edit/main/docs/
extra_javascript:
  - assets/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
